### PR TITLE
Space for Available reports

### PR DESCRIPTION
**Pull request by vishnu93tr**
Space for available tabs

### CODE REVIEW

**Comment by vishnu93tr** [comment]
@maciejmaciejewski can you please review this?

**Comment by Ekhart86** [comment]
Really necessary changes, please merge it.

**Comment by ymouhat** [comment]
Hi , is it possible to merge the change ? 
This is really blocking in terms of usability. 

THank you in advance

**Comment by maciejmaciejewski** [comment]
Hello, thanks for PR. I will review and test it as soon as possible.

**Comment by maciejmaciejewski** [comment]
Had to merge it to master to test it because of issues with the pipeline, however the result does not look good.
image

**Comment by vishnu93tr** [comment]
Its not working,will make some more code changes and test

**Comment by kristkat** [comment]
I also created a PR #82 to fix this issue

**Pull request merged**
